const SET_GET_QUESTIONS_STATUS = "UNI_TEST/SET_GET_QUESTIONS_STATUS";
const SET_GET_RESULT_STATUS = "UNI_TEST/SET_GET_RESULT_STATUS";
const SET_QUESTIONS = "UNI_TEST/SET_QUESTIONS";
const SET_QUESTIONS_ORIGIN = "UNI_TEST/SET_QUESTIONS_ORIGIN";
const SET_OPTIONS = "UNI_TEST/SET_OPTIONS";
const SET_PAGE_SIZE = "UNI_TEST/SET_PAGE_SIZE";
const SET_PAGE_INDEX = "UNI_TEST/SET_PAGE_INDEX";
const SET_TOTAL_QUESTIONS = "UNI_TEST/SET_TOTAL_QUESTIONS";
const SET_ANSWERS = "UNI_TEST/SET_ANSWERS";
const SET_PAGES_ANSWERED = "UNI_TEST/SET_PAGES_ANSWERED";
const SET_RESULT = "UNI_TEST/SET_RESULT";
const SET_KIND_CODE = "UNI_TEST/SET_KIND_CODE";
const SET_TEST_MSG = "UNI_TEST/SET_TEST_MSG";
const SET_QUESTION_KIND = "UNI_TEST/SET_QUESTION_KIND";
const SET_QUESTION_SET_ID = "UNI_TEST/SET_QUESTION_SET_ID";
const SET_TEST_PROGRESS = "UNI_TEST/SET_TEST_PROGRESS";
const RESET = "UNI_TEST/RESET";

export default {
    SET_GET_QUESTIONS_STATUS,
    SET_GET_RESULT_STATUS,
    SET_QUESTIONS,
    SET_QUESTIONS_ORIGIN,
    SET_OPTIONS,
    SET_PAGE_SIZE,
    SET_ANSWERS,
    SET_PAGE_INDEX,
    SET_TOTAL_QUESTIONS,
    SET_PAGES_ANSWERED,
    SET_RESULT,
    SET_KIND_CODE,
    SET_TEST_MSG,
    SET_QUESTION_KIND,
    SET_QUESTION_SET_ID,
    RESET,
    SET_TEST_PROGRESS
}