const SET_GET_QUESTIONS_STATUS = "UNI_TEST/SET_GET_QUESTIONS_STATUS";
const SET_GET_RESULT_STATUS = "UNI_TEST/SET_GET_RESULT_STATUS";
const SET_QUESTIONS = "UNI_TEST/SET_QUESTIONS";
const SET_QUESTIONS_ORIGIN = "UNI_TEST/SET_QUESTIONS_ORIGIN";
const SET_OPTIONS = "UNI_TEST/SET_OPTIONS";
const SET_PAGE_SIZE = "UNI_TEST/SET_PAGE_SIZE";
const SET_PAGE_INDEX = "UNI_TEST/SET_PAGE_INDEX";
const SET_TOTAL_QUESTIONS = "UNI_TEST/SET_TOTAL_QUESTIONS";
const SET_ANSWERS = "UNI_TEST/SET_ANSWERS";
const SET_PAGES_ANSWERED = "UNI_TEST/SET_PAGES_ANSWERED";
const SET_RESULT = "UNI_TEST/SET_RESULT";
const SET_KIND_CODE = "UNI_TEST/SET_KIND_CODE";
const SET_TEST_MSG = "UNI_TEST/SET_TEST_MSG";
const SET_QUESTION_KIND = "UNI_TEST/SET_QUESTION_KIND";
const SET_QUESTION_SET_ID = "UNI_TEST/SET_QUESTION_SET_ID";
const SET_TEST_PROGRESS = "UNI_TEST/SET_TEST_PROGRESS";
const SET_TOTAL_ANSWERED = "UNI_TEST/SET_TOTAL_ANSWERED";
const RESET = "UNI_TEST/RESET";
const SET_MAIN_MAJORS = "UNI_TEST/SET_MAIN_MAJORS";
const SET_SUB_MAJORS = "UNI_TEST/SET_SUB_MAJORS";
const SET_TREE_MAJORS = "UNI_TEST/SET_TREE_MAJORS";
const SET_UNI_RECOMMEND = "UNI_TEST/SET_UNI_RECOMMEND";
const SET_CHECKED_MAJORS = "UNI_TEST/SET_CHECKED_MAJORS";
const SET_POINT_FROM = "UNI_TEST/SET_POINT_FROM";
const SET_POINT_TO = "UNI_TEST/SET_POINT_TO";
const SET_UNIVERSITY_SEARCH = "UNI_TEST/SET_UNIVERSITY_SEARCH";
const SET_MAJORS = "UNI_TEST/SET_MAJORS";
const SET_CITY = "UNI_TEST/SET_CITY";
const SET_CITIES = "UNI_TEST/SET_CITIES";
const SET_TOTAL_UNIVERSITIES = "UNI_TEST/SET_TOTAL_UNIVERSITIES";
const RESET_FILTER = "UNI_TEST/RESET_FILTER";
const SET_CHECKED_MAJORS_DEFAULT = "UNI_TEST/SET_CHECKED_MAJORS_DEFAULT";
const SET_TOP_UNI_RECOMMEND = "UNI_TEST/SET_TOP_UNI_RECOMMEND";

export default {
    SET_TOTAL_UNIVERSITIES,
    SET_GET_QUESTIONS_STATUS,
    SET_GET_RESULT_STATUS,
    SET_QUESTIONS,
    SET_QUESTIONS_ORIGIN,
    SET_OPTIONS,
    SET_PAGE_SIZE,
    SET_ANSWERS,
    SET_PAGE_INDEX,
    SET_TOTAL_QUESTIONS,
    SET_PAGES_ANSWERED,
    SET_RESULT,
    SET_KIND_CODE,
    SET_TEST_MSG,
    SET_QUESTION_KIND,
    SET_QUESTION_SET_ID,
    RESET,
    SET_TEST_PROGRESS,
    SET_TOTAL_ANSWERED,
    SET_MAIN_MAJORS,
    SET_SUB_MAJORS,
    SET_TREE_MAJORS,
    SET_UNI_RECOMMEND,
    SET_CHECKED_MAJORS,
    SET_POINT_FROM,
    SET_POINT_TO,
    SET_UNIVERSITY_SEARCH,
    SET_MAJORS,
    SET_CITY,
    SET_CITIES,
    SET_CHECKED_MAJORS_DEFAULT,
    SET_TOP_UNI_RECOMMEND,
    RESET_FILTER
}