const SET_SIGNUP_STATUS = "SIGNUP/SET_SIGNUP_STATUS";
const SET_EMAIL = "SIGNUP/SET_EMAIL";
const SET_PASSWORD = "SIGNUP/SET_PASSWORD";
const SET_CONFIRMPASSWORD = "SIGNUP/SET_CONFIRMPASSWORD";
const SET_FULLNAME = "SIGNUP/SET_FULLNAME";
const SET_USER_DOB = "SIGNUP/SET_USER_DOB";

export default {
    SET_SIGNUP_STATUS,
    SET_EMAIL,
    SET_PASSWORD,
    SET_CONFIRMPASSWORD,
    SET_FULLNAME,
    SET_USER_DOB
}