const SET_CHECKED_MAJORS = "UNI_SEARCH/SET_CHECKED_MAJORS";
const SET_UNIVERSITIES = "UNI_SEARCH/SET_UNIVERSITIES";
const SET_SEARCH_UNIVERSITY_STATUS = "UNI_SEARCH/SET_SEARCH_UNIVERSITY_STATUS";
const SET_MAJORS = "UNI_SEARCH/SET_MAJORS";
const SET_GET_MAJORS_STATUS = "UNI_SEARCH/SET_GET_MAJORS_STATUS";
const SET_CITIES = "UNI_SEARCH/SET_CITIES";
const SET_GET_CITIES_STATUS = "UNI_SEARCH/SET_GET_CITIES_STATUS";
const SET_TOTAL_UNIVERSITIES = "UNI_SEARCH/SET_TOTAL_UNIVERSITIES";
const SET_UNIVERSITY_SEARCH = "UNI_SEARCH/SET_UNIVERSITY_SEARCH";
const SET_POINT_FROM = "UNI_SEARCH/SET_POINT_FROM";
const SET_POINT_TO = "UNI_SEARCH/SET_POINT_TO";
const SET_CITY = "UNI_SEARCH/SET_CITY";

export default {
    SET_CHECKED_MAJORS,
    SET_UNIVERSITIES,
    SET_SEARCH_UNIVERSITY_STATUS,
    SET_MAJORS,
    SET_GET_MAJORS_STATUS,
    SET_CITIES,
    SET_GET_CITIES_STATUS,
    SET_TOTAL_UNIVERSITIES,
    SET_UNIVERSITY_SEARCH,
    SET_POINT_FROM,
    SET_POINT_TO,
    SET_CITY
}