export default vars = {
    padding: 15,
    margin: 15,
    borderRadius: 50,
    bg: '#FBFBFD',
    navBg: 'rgba(255, 165, 0, 0.8)',
    borderColor: '#D9D9D9',
    borderColorDarker: '#D8DCE6',
    //shadow
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 5,
    //font
    appFont: "FontAwesome5_Regular",
    appBoldFont: "FontAwesome5_Solid",
    fontSizeSmall: 14,
    fontSizeStandard: 16,
    fontSizeLarge: 18,
    fontSizeHeading: 20,
    fontNormal: '400',
    fontMedium: '600',
    fontLightBold: '700',
    fontBold: '800',
    // text
    textMain: '#3E3F42',
    textBase: '#6B6C6F',
    textSecondary: '#9EA0A5',
    //----colors-----
    white: '#ffffff',
    green: '#c4df9b',
    blue: '#1665D8',
    orange: '#F6AB2F',
    red: '#E6492D',
    gray: '#959595',
    logo: '#d6561d',
    primaryHover: '#f7b13c',
    primaryActive: '#dd8d0a',
    warningHover: '#ff4b2c',
    warningActive: '#d42204',
}