const SET_EMAIL = "LOG_IN/SET_EMAIL";
const SET_PASSWORD = "LOG_IN/SET_PASSWORD";
const SET_LOG_IN_STATUS = "LOG_IN/SET_LOG_IN_STATUS";
const SET_USER = "LOG_IN/SET_USER";
const SET_STORAGE = "LOG_IN/SET_STORAGE";
const CLEAR_LOG_IN = "LOG_IN/CLEAR_LOG_IN";
const SET_FORM_ERROR = "LOG_IN/SET_FORM_ERROR";

export default {
    SET_EMAIL,
    SET_PASSWORD,
    SET_LOG_IN_STATUS,
    SET_USER,
    SET_STORAGE,
    CLEAR_LOG_IN,
    SET_FORM_ERROR
}