const SET_FIRST_NAME = 'PROFILE/SET_FIRST_NAME';
const SET_AVATAR = 'PROFILE/SET_AVATAR';
const SET_GET_PROFILE_STATUS = 'PROFILE/SET_GET_PROFILE_STATUS';
const SET_USER_FULL_NAME = 'PROFILE/SET_USER_FULL_NAME';
const SET_CHANGE_USER_FULL_NAME = 'PROFILE/SET_CHANGE_USER_FULL_NAME';
const SET_PROFILE = 'PROFILE/SET_PROFILE';
const SET_USER_DOB = 'PROFILE/SET_USER_DOB';
const SET_CHANGE_USER_DOB = 'PROFILE/SET_CHANGE_USER_DOB';
const SET_UPDATE_PROFILE_STATUS = 'PROFILE/SET_UPDATE_PROFILE_STATUS';
const SET_CURRENT_PASSWORD = 'PROFILE/SET_CURRENT_PASSWORD';
const SET_NEW_PASSWORD = 'PROFILE/SET_NEW_PASSWORD';
const SET_RE_NEW_PASSWORD = 'PROFILE/SET_RE_NEW_PASSWORD';
const SET_UPDATE_PASSWORD_STATUS = 'PROFILE/SET_UPDATE_PASSWORD_STATUS';
const SET_UPDATE_PASSWORD_FORM_ERROR = 'PROFILE/SET_UPDATE_PASSWORD_FORM_ERROR';
const SET_UPDATE_PROFILE_FORM_ERROR = 'PROFILE/SET_UPDATE_PROFILE_FORM_ERROR';
const SET_UPLOAD_TEMP_IMAGE_STATUS = 'PROFILE/SET_UPLOAD_TEMP_IMAGE_STATUS';
const SET_UPLOAD_TEMP_IMAGE_ERROR = 'PROFILE/SET_UPLOAD_TEMP_IMAGE_ERROR';
const SET_UPLOAD_IMAGE_STATUS = 'PROFILE/SET_UPLOAD_IMAGE_STATUS';
const SET_UPLOAD_IMAGE_ERROR = 'PROFILE/SET_UPLOAD_IMAGE_ERROR';
const RESET_EDIT_FORM = "PROFILE/RESET_EDIT_FORM";

export default {
    SET_FIRST_NAME,
    SET_AVATAR,
    SET_GET_PROFILE_STATUS,
    SET_USER_FULL_NAME,
    SET_CHANGE_USER_FULL_NAME,
    SET_PROFILE,
    SET_UPDATE_PROFILE_STATUS,
    SET_CURRENT_PASSWORD,
    SET_NEW_PASSWORD,
    SET_RE_NEW_PASSWORD,
    SET_USER_DOB,
    SET_CHANGE_USER_DOB,
    SET_UPLOAD_TEMP_IMAGE_STATUS,
    SET_UPLOAD_TEMP_IMAGE_ERROR,
    SET_UPLOAD_IMAGE_STATUS,
    SET_UPLOAD_IMAGE_ERROR,
    SET_UPDATE_PASSWORD_STATUS,
    SET_UPDATE_PASSWORD_FORM_ERROR,
    SET_UPDATE_PROFILE_FORM_ERROR,
    RESET_EDIT_FORM
}