const SET_FIRST_NAME = 'PROFILE/SET_FIRST_NAME';
const SET_AVATAR = 'PROFILE/SET_AVATAR';
const SET_GET_PROFILE_STATUS = 'PROFILE/SET_GET_PROFILE_STATUS';
const SET_USER_FULL_NAME = 'PROFILE/SET_USER_FULL_NAME';
const SET_CHANGE_USER_FULL_NAME = 'PROFILE/SET_CHANGE_USER_FULL_NAME';
const SET_PROFILE = 'PROFILE/SET_PROFILE';
const SET_USER_DOB = 'PROFILE/SET_USER_DOB';
const SET_CHANGE_USER_DOB = 'PROFILE/SET_CHANGE_USER_DOB';
const SET_UPDATE_PROFILE_STATUS = 'PROFILE/SET_UPDATE_PROFILE_STATUS';
const SET_CURRENT_PASSWORD = 'PROFILE/SET_CURRENT_PASSWORD';
const SET_NEW_PASSWORD = 'PROFILE/SET_NEW_PASSWORD';
const SET_RE_NEW_PASSWORD = 'PROFILE/SET_RE_NEW_PASSWORD';
const SET_UPDATE_PASSWORD_STATUS = 'PROFILE/SET_UPDATE_PASSWORD_STATUS';
const SET_UPDATE_PASSWORD_FORM_ERROR = 'PROFILE/SET_UPDATE_PASSWORD_FORM_ERROR';
const SET_UPDATE_PROFILE_FORM_ERROR = 'PROFILE/SET_UPDATE_PROFILE_FORM_ERROR';
const SET_UPLOAD_TEMP_IMAGE_STATUS = 'PROFILE/SET_UPLOAD_TEMP_IMAGE_STATUS';
const SET_UPLOAD_TEMP_IMAGE_ERROR = 'PROFILE/SET_UPLOAD_TEMP_IMAGE_ERROR';
const SET_UPLOAD_IMAGE_STATUS = 'PROFILE/SET_UPLOAD_IMAGE_STATUS';
const SET_UPLOAD_IMAGE_ERROR = 'PROFILE/SET_UPLOAD_IMAGE_ERROR';
const SET_GET_TEST_RESULT_BY_USER_ID = 'PROFILE/SET_GET_TEST_RESULT_BY_USER_ID';
const RESET_EDIT_FORM = "PROFILE/RESET_EDIT_FORM";
const SET_RESULT = "PROFILE/SET_RESULT";
const SET_KIND_CODE = "PROFILE/SET_KIND_CODE";
const SET_TEST_MSG = "PROFILE/SET_TEST_MSG";
const RESET = "PROFILE/RESET";
const SET_MAIN_MAJORS = "PROFILE/SET_MAIN_MAJORS";
const SET_SUB_MAJORS = "PROFILE/SET_SUB_MAJORS";
const SET_TREE_MAJORS = "PROFILE/SET_TREE_MAJORS";
const SET_UNI_RECOMMEND = "PROFILE/SET_UNI_RECOMMEND";
const SET_CHECKED_MAJORS = "PROFILE/SET_CHECKED_MAJORS";
const SET_POINT_FROM = "PROFILE/SET_POINT_FROM";
const SET_POINT_TO = "PROFILE/SET_POINT_TO";
const SET_UNIVERSITY_SEARCH = "PROFILE/SET_UNIVERSITY_SEARCH";
const SET_MAJORS = "PROFILE/SET_MAJORS";
const SET_CITY = "PROFILE/SET_CITY";
const SET_CITIES = "PROFILE/SET_CITIES";
const SET_TOTAL_UNIVERSITIES = "PROFILE/SET_TOTAL_UNIVERSITIES";
const RESET_FILTER = "PROFILE/RESET_FILTER";
const SET_CHECKED_MAJORS_DEFAULT = "PROFILE/SET_CHECKED_MAJORS_DEFAULT";
const SET_TOP_UNI_RECOMMEND = "PROFILE/SET_TOP_UNI_RECOMMEND";
const SET_CHECK_VERIFIED_STATUS = "PROFILE/SET_CHECK_VERIFIED_STATUS";

export default {
    SET_FIRST_NAME,
    SET_AVATAR,
    SET_GET_PROFILE_STATUS,
    SET_USER_FULL_NAME,
    SET_CHANGE_USER_FULL_NAME,
    SET_PROFILE,
    SET_UPDATE_PROFILE_STATUS,
    SET_CURRENT_PASSWORD,
    SET_NEW_PASSWORD,
    SET_RE_NEW_PASSWORD,
    SET_USER_DOB,
    SET_CHANGE_USER_DOB,
    SET_UPLOAD_TEMP_IMAGE_STATUS,
    SET_UPLOAD_TEMP_IMAGE_ERROR,
    SET_UPLOAD_IMAGE_STATUS,
    SET_UPLOAD_IMAGE_ERROR,
    SET_UPDATE_PASSWORD_STATUS,
    SET_UPDATE_PASSWORD_FORM_ERROR,
    SET_UPDATE_PROFILE_FORM_ERROR,
    SET_GET_TEST_RESULT_BY_USER_ID,
    RESET_EDIT_FORM,
    SET_RESULT,
    SET_KIND_CODE,
    SET_TEST_MSG,
    RESET,
    SET_MAIN_MAJORS,
    SET_SUB_MAJORS,
    SET_TREE_MAJORS,
    SET_UNI_RECOMMEND,
    SET_CHECKED_MAJORS,
    SET_POINT_FROM,
    SET_POINT_TO,
    SET_UNIVERSITY_SEARCH,
    SET_MAJORS,
    SET_CITY,
    SET_CITIES,
    SET_TOTAL_UNIVERSITIES,
    RESET_FILTER,
    SET_CHECKED_MAJORS_DEFAULT,
    SET_TOP_UNI_RECOMMEND,
    SET_CHECK_VERIFIED_STATUS
}